# -*- coding: utf-8 -*-
"""Chatbot_Gemini_Test 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IJ8CD2RPpJcgLEbzo_L97nBcmpOvv3k9
"""

import streamlit as st
import google.generativeai as genai

# Set up Gemini API key
genai.configure(api_key="AIzaSyBUsXmmFh0E5DcwX15uwY9rzgb_ZPsa5V4")

# Chatbot function
def chat_with_gemini(prompt):
    model = genai.GenerativeModel("gemini-pro")
    response = model.generate_content(prompt)
    return response.text

# Streamlit App UI
st.title("🤖 Free AI Chatbot (Powered by Gemini)")
st.write("Ask me anything!")

user_input = st.text_input("You:", "")

if st.button("Send"):
    if user_input:
        response = chat_with_gemini(user_input)
        st.text_area("AI:", response, height=200)
    else:
        st.warning("Please enter a message.")